/**
 * AES-GCM room key — generated by host, shared via URL hash fragment.
 * Hash fragment is never sent to the server (browser spec).
 * Used to E2E-encrypt clipboard content that flows through signaling.
 */
export class RoomCrypto {
  private constructor(private key: CryptoKey) {}

  /** Generate a new AES-256-GCM key and return both the CryptoKey and its base64url export. */
  static async generate(): Promise<{ crypto: RoomCrypto; keyB64: string }> {
    const key = await crypto.subtle.generateKey(
      { name: 'AES-GCM', length: 256 },
      true,
      ['encrypt', 'decrypt'],
    );
    const raw = await crypto.subtle.exportKey('raw', key);
    const keyB64 = btoa(String.fromCharCode(...new Uint8Array(raw)));
    return { crypto: new RoomCrypto(key), keyB64 };
  }

  /** Import a key from the base64 string found in the URL hash. */
  static async fromBase64(b64: string): Promise<RoomCrypto> {
    const raw = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
    const key = await crypto.subtle.importKey(
      'raw', raw,
      { name: 'AES-GCM', length: 256 },
      false,
      ['encrypt', 'decrypt'],
    );
    return new RoomCrypto(key);
  }

  /** Encrypt UTF-8 text → base64 ciphertext (IV prepended). */
  async encrypt(plaintext: string): Promise<string> {
    const iv  = crypto.getRandomValues(new Uint8Array(12));
    const enc = new TextEncoder().encode(plaintext);
    const ct  = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, this.key, enc);
    const out = new Uint8Array(12 + ct.byteLength);
    out.set(iv, 0);
    out.set(new Uint8Array(ct), 12);
    return btoa(String.fromCharCode(...out));
  }

  /** Decrypt base64 ciphertext → UTF-8 text. Returns null on failure (wrong key / corrupt). */
  async decrypt(ciphertext: string): Promise<string | null> {
    try {
      const buf = Uint8Array.from(atob(ciphertext), c => c.charCodeAt(0));
      const iv  = buf.slice(0, 12);
      const ct  = buf.slice(12);
      const pt  = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, this.key, ct);
      return new TextDecoder().decode(pt);
    } catch {
      return null;
    }
  }
}

/** Extract key from URL hash (#key=...) and build RoomCrypto instance, or null if absent. */
export async function roomCryptoFromHash(): Promise<RoomCrypto | null> {
  const hash = new URLSearchParams(location.hash.slice(1));
  const keyB64 = hash.get('key');
  if (!keyB64) return null;
  try { return await RoomCrypto.fromBase64(keyB64); } catch { return null; }
}
